/** Texty kroku Priečinok a obrazovky „Toto som našiel“ (SK, CS, EN, DE). */
import type { Language } from "@/i18n";

const sk = {
  folderTitle: "Priečinok",
  folderLead: "LAWOSS pracuje nad vaším priečinkom, rovnako ako Claude Code alebo Codex. Vyberte existujúci, alebo začnite nanovo.",
  connectExisting: "Pripojiť existujúci priečinok",
  connectExistingHint: "Klient, celá prax alebo jedna vec. Rozpoznám to a spýtam sa.",
  startFresh: "Začať nanovo",
  startFreshHint: "Nový priečinok LAWOSS s kanceláriou. Klientov doň neskôr skopírujete.",
  choose: "Vybrať priečinok",
  freshDone: "Priečinok LAWOSS je pripravený: kancelária v Office/ a priečinok Klienti/.",
  freshHowTo: "Klientov sem skopírujte (pôvodné priečinky ostanú nedotknuté) a v bočnom paneli zvoľte Pridať priečinok. Každého klienta potom usporiadate podľa OKF hromadne alebo po jednom.",
  freshNotEmpty: "Vyberte prázdny priečinok. V okne výberu môžete vytvoriť nový.",
  finish: "Dokončiť",
  looking: "Prezerám priečinok…",
  foundTitle: "Toto som našiel",
  clientFound: "Vyzerá to ako klient {name}.",
  practiceFound: "Vyzerá to ako celá prax: {count} klientov.",
  matterFound: "Vyzerá to ako jedna vec: {name}.",
  unknownFound: "Neviem s istotou, čo tento priečinok je.",
  incomplete: "Priečinok je veľký, prezrel som len časť. Návrh nemusí byť úplný.",
  correctLabel: "Toto je",
  asClient: "klient",
  asPractice: "celá prax",
  asMatter: "jedna vec",
  matterHint: "Vec patrí pod klienta. Pripojím nadradený priečinok {name} ako klienta.",
  useParent: "Pripojiť klienta {name}",
  scopeTitle: "Ako pracovať s praxou",
  scopeEach: "Každý klient zvlášť (odporúčané)",
  scopeEachHint: "Agent vidí vždy len jedného klienta.",
  scopeOne: "Jeden priečinok pre všetko",
  scopeOneHint: "Model môže v jednej konverzácii čítať spisy rôznych klientov. Zvoľte len vedome (mlčanlivosť).",
  clientsTitle: "Klienti",
  selectAll: "Označiť všetkých",
  selectNone: "Zrušiť označenie",
  reorganizeQuestion: "Môžem priečinok usporiadať podľa OKF?",
  okfNotice: "Do priečinka pribudnú súbory OKF (AGENTS.md, CLAUDE.md, karta klienta, memory/). Vďaka nim každý AI nástroj vie, čo v priečinku je. Žiadny váš súbor sa neprepíše ani nezmaže.",
  answerNo: "Nie, len pridaj OKF súbory",
  answerNoHint: "Nič existujúce sa nepohne.",
  answerYes: "Áno, usporiadaj",
  answerYesHint: "Najprv pridám OKF súbory, potom ukážem, kam navrhujem dokumenty presunúť. Presun sa dá vrátiť.",
  answerYesPractice: "Najprv pridám OKF súbory všetkým označeným klientom, potom navrhnem presuny po jednom klientovi.",
  answerYesDisabled: "Celú prax ako jeden priečinok usporiadať nejde. Klientov usporiadate neskôr jednotlivo.",
  filesTitle: "Pribudne",
  acknowledge: "Beriem na vedomie a pokračujem",
  working: "Pridávam OKF súbory: {done} z {total}",
  batchDone: "Hotovo: {done} z {total}",
  batchFailed: "Nepodarilo sa: {name} ({error})",
  retry: "Skúsiť znova neúspešných",
  reorganizeFor: "Usporiadanie: {name}",
  skipClient: "Tohto klienta preskočiť",
  nextClient: "Ďalší klient",
  reorganized: "Usporiadané. Presun sa dá vrátiť na stránke Roztriedenie.",
  open: "Otvoriť v LAWOSS",
  back: "Späť",
  changeFolder: "Vybrať iný priečinok",
};
type FoundTextKey = keyof typeof sk;
type Dictionary = Record<FoundTextKey, string>;

const cs: Dictionary = {
  folderTitle: "Složka",
  folderLead: "LAWOSS pracuje nad vaší složkou, stejně jako Claude Code nebo Codex. Vyberte existující, nebo začněte znovu.",
  connectExisting: "Připojit existující složku",
  connectExistingHint: "Klient, celá praxe nebo jedna věc. Rozpoznám to a zeptám se.",
  startFresh: "Začít znovu",
  startFreshHint: "Nová složka LAWOSS s kanceláří. Klienty do ní později zkopírujete.",
  choose: "Vybrat složku",
  freshDone: "Složka LAWOSS je připravená: kancelář v Office/ a složka Klienti/.",
  freshHowTo: "Klienty sem zkopírujte (původní složky zůstanou nedotčené) a v bočním panelu zvolte Přidat složku. Každého klienta pak uspořádáte podle OKF hromadně nebo po jednom.",
  freshNotEmpty: "Vyberte prázdnou složku. V okně výběru můžete vytvořit novou.",
  finish: "Dokončit",
  looking: "Prohlížím složku…",
  foundTitle: "Tohle jsem našel",
  clientFound: "Vypadá to jako klient {name}.",
  practiceFound: "Vypadá to jako celá praxe: {count} klientů.",
  matterFound: "Vypadá to jako jedna věc: {name}.",
  unknownFound: "Nevím s jistotou, co tato složka je.",
  incomplete: "Složka je velká, prohlédl jsem jen část. Návrh nemusí být úplný.",
  correctLabel: "Tohle je",
  asClient: "klient",
  asPractice: "celá praxe",
  asMatter: "jedna věc",
  matterHint: "Věc patří pod klienta. Připojím nadřazenou složku {name} jako klienta.",
  useParent: "Připojit klienta {name}",
  scopeTitle: "Jak pracovat s praxí",
  scopeEach: "Každý klient zvlášť (doporučeno)",
  scopeEachHint: "Agent vidí vždy jen jednoho klienta.",
  scopeOne: "Jedna složka pro všechno",
  scopeOneHint: "Model může v jedné konverzaci číst spisy různých klientů. Zvolte jen vědomě (mlčenlivost).",
  clientsTitle: "Klienti",
  selectAll: "Označit všechny",
  selectNone: "Zrušit označení",
  reorganizeQuestion: "Můžu složku uspořádat podle OKF?",
  okfNotice: "Do složky přibudou soubory OKF (AGENTS.md, CLAUDE.md, karta klienta, memory/). Díky nim každý AI nástroj ví, co ve složce je. Žádný váš soubor se nepřepíše ani nesmaže.",
  answerNo: "Ne, jen přidej soubory OKF",
  answerNoHint: "Nic existujícího se nepohne.",
  answerYes: "Ano, uspořádej",
  answerYesHint: "Nejdřív přidám soubory OKF, potom ukážu, kam navrhuji dokumenty přesunout. Přesun jde vrátit.",
  answerYesPractice: "Nejdřív přidám soubory OKF všem označeným klientům, potom navrhnu přesuny po jednom klientovi.",
  answerYesDisabled: "Celou praxi jako jednu složku uspořádat nejde. Klienty uspořádáte později jednotlivě.",
  filesTitle: "Přibude",
  acknowledge: "Beru na vědomí a pokračuji",
  working: "Přidávám soubory OKF: {done} z {total}",
  batchDone: "Hotovo: {done} z {total}",
  batchFailed: "Nepodařilo se: {name} ({error})",
  retry: "Zkusit znovu neúspěšné",
  reorganizeFor: "Uspořádání: {name}",
  skipClient: "Tohoto klienta přeskočit",
  nextClient: "Další klient",
  reorganized: "Uspořádáno. Přesun jde vrátit na stránce Roztřídění.",
  open: "Otevřít v LAWOSS",
  back: "Zpět",
  changeFolder: "Vybrat jinou složku",
};

const en: Dictionary = {
  folderTitle: "Folder",
  folderLead: "LAWOSS works on your folder, just like Claude Code or Codex. Choose an existing one or start fresh.",
  connectExisting: "Connect an existing folder",
  connectExistingHint: "A client, a whole practice or one matter. I will recognise it and ask.",
  startFresh: "Start fresh",
  startFreshHint: "A new LAWOSS folder with an office. You copy clients into it later.",
  choose: "Choose folder",
  freshDone: "The LAWOSS folder is ready: the office in Office/ and the Klienti/ folder.",
  freshHowTo: "Copy clients here (the original folders stay untouched) and choose Add folder in the sidebar. Then organise each client by OKF, all at once or one by one.",
  freshNotEmpty: "Choose an empty folder. You can create a new one in the picker.",
  finish: "Finish",
  looking: "Looking at the folder…",
  foundTitle: "Here is what I found",
  clientFound: "This looks like the client {name}.",
  practiceFound: "This looks like a whole practice: {count} clients.",
  matterFound: "This looks like one matter: {name}.",
  unknownFound: "I am not sure what this folder is.",
  incomplete: "The folder is large and I only looked at part of it. The suggestion may be incomplete.",
  correctLabel: "This is",
  asClient: "a client",
  asPractice: "a whole practice",
  asMatter: "one matter",
  matterHint: "A matter belongs to a client. I will connect the parent folder {name} as the client.",
  useParent: "Connect client {name}",
  scopeTitle: "How to work with the practice",
  scopeEach: "Each client separately (recommended)",
  scopeEachHint: "The agent only ever sees one client.",
  scopeOne: "One folder for everything",
  scopeOneHint: "The model may read different clients' files in one conversation. Choose this knowingly (confidentiality).",
  clientsTitle: "Clients",
  selectAll: "Select all",
  selectNone: "Clear selection",
  reorganizeQuestion: "May I organise the folder by OKF?",
  okfNotice: "OKF files will be added to the folder (AGENTS.md, CLAUDE.md, client card, memory/). With them, any AI tool knows what the folder contains. None of your files is overwritten or deleted.",
  answerNo: "No, just add OKF files",
  answerNoHint: "Nothing existing moves.",
  answerYes: "Yes, organise it",
  answerYesHint: "First I add the OKF files, then I show where I suggest moving documents. The move can be undone.",
  answerYesPractice: "First I add OKF files to all selected clients, then I suggest moves one client at a time.",
  answerYesDisabled: "A whole practice as one folder cannot be organised. Organise clients one by one later.",
  filesTitle: "Will be added",
  acknowledge: "I acknowledge this and continue",
  working: "Adding OKF files: {done} of {total}",
  batchDone: "Done: {done} of {total}",
  batchFailed: "Failed: {name} ({error})",
  retry: "Retry the failed ones",
  reorganizeFor: "Organising: {name}",
  skipClient: "Skip this client",
  nextClient: "Next client",
  reorganized: "Organised. The move can be undone on the Sorting page.",
  open: "Open in LAWOSS",
  back: "Back",
  changeFolder: "Choose another folder",
};

const de: Dictionary = {
  folderTitle: "Ordner",
  folderLead: "LAWOSS arbeitet mit Ihrem Ordner, wie Claude Code oder Codex. Wählen Sie einen bestehenden oder beginnen Sie neu.",
  connectExisting: "Bestehenden Ordner verbinden",
  connectExistingHint: "Ein Mandant, eine ganze Kanzlei oder eine Angelegenheit. Ich erkenne es und frage nach.",
  startFresh: "Neu beginnen",
  startFreshHint: "Ein neuer LAWOSS-Ordner mit Kanzlei. Mandanten kopieren Sie später hinein.",
  choose: "Ordner wählen",
  freshDone: "Der LAWOSS-Ordner ist bereit: die Kanzlei in Office/ und der Ordner Klienti/.",
  freshHowTo: "Kopieren Sie Mandanten hierher (die ursprünglichen Ordner bleiben unberührt) und wählen Sie in der Seitenleiste Ordner hinzufügen. Ordnen Sie dann jeden Mandanten nach OKF, alle auf einmal oder einzeln.",
  freshNotEmpty: "Wählen Sie einen leeren Ordner. Im Auswahlfenster können Sie einen neuen anlegen.",
  finish: "Fertig",
  looking: "Ich sehe mir den Ordner an…",
  foundTitle: "Das habe ich gefunden",
  clientFound: "Das sieht aus wie der Mandant {name}.",
  practiceFound: "Das sieht aus wie eine ganze Kanzlei: {count} Mandanten.",
  matterFound: "Das sieht aus wie eine Angelegenheit: {name}.",
  unknownFound: "Ich bin nicht sicher, was dieser Ordner ist.",
  incomplete: "Der Ordner ist groß, ich habe nur einen Teil angesehen. Der Vorschlag ist evtl. unvollständig.",
  correctLabel: "Das ist",
  asClient: "ein Mandant",
  asPractice: "eine ganze Kanzlei",
  asMatter: "eine Angelegenheit",
  matterHint: "Eine Angelegenheit gehört zu einem Mandanten. Ich verbinde den übergeordneten Ordner {name} als Mandanten.",
  useParent: "Mandant {name} verbinden",
  scopeTitle: "Wie mit der Kanzlei arbeiten",
  scopeEach: "Jeder Mandant einzeln (empfohlen)",
  scopeEachHint: "Der Agent sieht immer nur einen Mandanten.",
  scopeOne: "Ein Ordner für alles",
  scopeOneHint: "Das Modell kann in einem Gespräch Akten verschiedener Mandanten lesen. Nur bewusst wählen (Verschwiegenheit).",
  clientsTitle: "Mandanten",
  selectAll: "Alle auswählen",
  selectNone: "Auswahl aufheben",
  reorganizeQuestion: "Darf ich den Ordner nach OKF ordnen?",
  okfNotice: "Dem Ordner werden OKF-Dateien hinzugefügt (AGENTS.md, CLAUDE.md, Mandantenkarte, memory/). Damit weiß jedes KI-Werkzeug, was der Ordner enthält. Keine Ihrer Dateien wird überschrieben oder gelöscht.",
  answerNo: "Nein, nur OKF-Dateien hinzufügen",
  answerNoHint: "Nichts Bestehendes wird verschoben.",
  answerYes: "Ja, ordnen",
  answerYesHint: "Zuerst füge ich die OKF-Dateien hinzu, dann zeige ich, wohin ich Dokumente verschieben würde. Das Verschieben lässt sich rückgängig machen.",
  answerYesPractice: "Zuerst füge ich allen ausgewählten Mandanten OKF-Dateien hinzu, dann schlage ich Verschiebungen Mandant für Mandant vor.",
  answerYesDisabled: "Eine ganze Kanzlei als ein Ordner lässt sich nicht ordnen. Ordnen Sie Mandanten später einzeln.",
  filesTitle: "Wird hinzugefügt",
  acknowledge: "Ich nehme das zur Kenntnis und fahre fort",
  working: "Füge OKF-Dateien hinzu: {done} von {total}",
  batchDone: "Fertig: {done} von {total}",
  batchFailed: "Fehlgeschlagen: {name} ({error})",
  retry: "Fehlgeschlagene erneut versuchen",
  reorganizeFor: "Ordnen: {name}",
  skipClient: "Diesen Mandanten überspringen",
  nextClient: "Nächster Mandant",
  reorganized: "Geordnet. Das Verschieben lässt sich auf der Seite Sortierung rückgängig machen.",
  open: "In LAWOSS öffnen",
  back: "Zurück",
  changeFolder: "Anderen Ordner wählen",
};

export const FOUND_TEXT: Record<"sk" | "cs" | "en" | "de", Dictionary> = { sk, cs, en, de };
export type { FoundTextKey };

export function foundText(locale: Language): (key: FoundTextKey, params?: Record<string, string | number>) => string {
  const dictionary = locale === "sk" || locale === "cs" || locale === "de" ? FOUND_TEXT[locale] : FOUND_TEXT.en;
  return (key, params) => dictionary[key].replace(/\{(\w+)\}/g, (match, name: string) => (params && name in params ? String(params[name]) : match));
}
